# 10-714 Homework 2

In this homework, you will be implementing a neural network library in the needle framework. Reminder: __you must save a copy in drive__.

In [1]:
# Code to set up the assignment
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive/
!mkdir -p 10714
%cd /content/drive/MyDrive/10714
# !git clone https://github.com/dlsys10714/hw2.git
%cd /content/drive/MyDrive/10714/hw2

!pip3 install --upgrade --no-deps git+https://github.com/dlsys10714/mugrade.git

Mounted at /content/drive
/content/drive/MyDrive
/content/drive/MyDrive/10714
/content/drive/MyDrive/10714/hw2
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning https://github.com/dlsys10714/mugrade.git to /tmp/pip-req-build-wfa6db7s
  Running command git clone -q https://github.com/dlsys10714/mugrade.git /tmp/pip-req-build-wfa6db7s
  Created wheel for mugrade: filename=mugrade-1.2-py3-none-any.whl size=3970 sha256=b2f4cc5482d3241fed6c9a100126a06ca2728e3d85199ebde3246d325bee399c
  Stored in directory: /tmp/pip-ephem-wheel-cache-gg136k_0/wheels/15/84/8e/0b0cd7631b7172a69b25dffca173268d4f66e81e0e70f9e79e
Successfully built mugrade


## Question 0

This homework builds off of Homework 1. First, in your Homework 2 directory, go to the files `autograd.py`, `ops.py` in the `python/needle` directory, and fill in the code between `### BEGIN YOUR SOLUTION` and `### END YOUR SOLUTION` with your solutions from Homework 1. 

**Note:** We have added functionality since HW1, specifically in the `autograd.py` file, so it is important to copy over your solutions rather than the entire previous file.

In [2]:
import sys
sys.path.append('./python')
sys.path.append('./apps')

## Question 1

In this first question, you will implement a few different methods for weight initialization.  This will be done in the `python/needle/init.py` file, which contains a number of routines for initializing needle Tensors using various random and constant initializations.  Following the same methodology of the existing initializers (you will want to call e.g. `init.rand` or `init.randn` from your functions below, implement the following common initialization methods.  In all cases, the functions should return `fan_in` by `fan_out` 2D tensors (extensions to other sizes can be done via e.g., reshaping).


### Xavier uniform
`xavier_uniform(fan_in, fan_out, gain=1.0, **kwargs)`

Fills the input Tensor with values according to the method described in [Understanding the difficulty of training deep feedforward neural networks](https://proceedings.mlr.press/v9/glorot10a/glorot10a.pdf), using a uniform distribution. The resulting Tensor will have values sampled from $\mathcal{U}(-a, a)$ where 
\begin{equation}
a = \text{gain} \times \sqrt{\frac{6}{\text{fan_in} + \text{fan_out}}}
\end{equation}

Pass remaining `**kwargs` parameters to the corresponding `init` random call.

##### Parameters
- `fan_in` - dimensionality of input
- `fan_out` - dimensionality of output
- `gain` - optional scaling factor
___

### Xavier normal
`xavier_normal(fan_in, fan_out, gain=1.0, **kwargs)`

Fills the input Tensor with values according to the method described in [Understanding the difficulty of training deep feedforward neural networks](https://proceedings.mlr.press/v9/glorot10a/glorot10a.pdf), using a normal distribution. The resulting Tensor will have values sampled from $\mathcal{N}(0, \text{std}^2)$ where 
\begin{equation}
\text{std} = \text{gain} \times \sqrt{\frac{2}{\text{fan_in} + \text{fan_out}}}
\end{equation}

##### Parameters
- `fan_in` - dimensionality of input
- `fan_out` - dimensionality of output
- `gain` - optional scaling factor
___

### Kaiming uniform
`kaiming_uniform(fan_in, fan_out, nonlinearity="relu", **kwargs)`

Fills the input Tensor with values according to the method described in [Delving deep into rectifiers: Surpassing human-level performance on ImageNet classification](https://arxiv.org/pdf/1502.01852.pdf), using a uniform distribution. The resulting Tensor will have values sampled from $\mathcal{U}(-\text{bound}, \text{bound})$ where 
\begin{equation}
\text{bound} = \text{gain} \times \sqrt{\frac{3}{\text{fan_in}}}
\end{equation}

Use the recommended gain value for ReLU: $\text{gain}=\sqrt{2}$.

##### Parameters
- `fan_in` - dimensionality of input
- `fan_out` - dimensionality of output
- `nonlinearity` - the non-linear function
___

### Kaiming normal
`kaiming_normal(fan_in, fan_out, nonlinearity="relu", **kwargs)`

Fills the input Tensor with values according to the method described in [Delving deep into rectifiers: Surpassing human-level performance on ImageNet classification](https://arxiv.org/pdf/1502.01852.pdf), using a uniform distribution. The resulting Tensor will have values sampled from $\mathcal{N}(0, \text{std}^2)$ where 
\begin{equation}
\text{std} = \frac{\text{gain}}{\sqrt{\text{fan_in}}}
\end{equation}

Use the recommended gain value for ReLU: $\text{gain}=\sqrt{2}$.

##### Parameters
- `fan_in` - dimensionality of input
- `fan_out` - dimensionality of output
- `nonlinearity` - the non-linear function

In [ ]:
!python3 -m pytest -v -k "test_init"

============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 90 items / 86 deselected                                             

tests/test_nn_and_optim.py::test_init_kaiming_uniform PASSED             [ 25%]
tests/test_nn_and_optim.py::test_init_kaiming_normal PASSED              [ 50%]
tests/test_nn_and_optim.py::test_init_xavier_uniform PASSED              [ 75%]
tests/test_nn_and_optim.py::test_init_xavier_normal PASSED               [100%]

=================== 4 passed, 86 deselected in 0.48 seconds ====================


In [ ]:
!python -m mugrade submit '_7GqfAa2TKxH2yZHzgsAa' -k "init" -s

submit
============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 18 items / 17 deselected                                             

tests/test_nn_and_optim.py 
Submitting init...
Grader test 1 passed
Grader test 2 passed
Grader test 3 passed
Grader test 4 passed
.

=================== 1 passed, 17 deselected in 5.45 seconds ====================


## Question 2

In this question, you will implement additional modules in `python/needle/nn.py`. Specifically, for the following modules described below, initialize any variables of the module in the constructor, and fill out the `forward` method. 
___

### Linear
`needle.nn.Linear(in_features, out_features, bias=True, device=None, dtype="float32")`

Applies a linear transformation to the incoming data: $y = xA^T + b$. The input shape is $(N, H_{in})$ where $H_{in}=\text{in_features}$. The output shape is $(N, H_{out})$ where $H_{out}=\text{out_features}$.

Be careful to explicitly broadcast the bias term to the correct shape -- Needle does not support implicit broadcasting.

Additionally note that, for all layers including this one, you should initialize the weight Tensor before the bias Tensor, and should initialize all Parameters using only functions from 'init'.

##### Parameters
- `in_features` - size of each input sample
- `out_features` - size of each output sample
- `bias` - If set to `False`, the layer will not learn an additive bias.

##### Variables
- `weight` - the learnable weights of shape (`in_features`, `out_features`). The values should be initialized with the Kaiming Uniform initialization with `fan_in = in_features`
- `bias` - the learnable bias of shape (`out_features`). The values should be initialized with the Kaiming Uniform initialize with `fan_in = out_features`. **Note the different in fan_in choice, due to their relative sizes**. 

In [ ]:
!python3 -m pytest -v -k "test_nn_linear"

============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 90 items / 82 deselected                                             

tests/test_nn_and_optim.py::test_nn_linear_weight_init_1 PASSED          [ 12%]
tests/test_nn_and_optim.py::test_nn_linear_bias_init_1 PASSED            [ 25%]
tests/test_nn_and_optim.py::test_nn_linear_forward_1 PASSED              [ 37%]
tests/test_nn_and_optim.py::test_nn_linear_forward_2 PASSED              [ 50%]
tests/test_nn_and_optim.py::test_nn_linear_forward_3 PASSED              [ 62%]
tests/test_nn_and_optim.py::test_nn_linear_backward_1 PASSED             [ 75%]
tests/test_nn_and_optim.py::test_nn_linear_backward_2 PASSED             [ 87%]
tests/test_nn_and_optim.py::test_nn_linear_backward_3 PASSED             [100%]

=====

In [ ]:
!python -m mugrade submit '_7GqfAa2TKxH2yZHzgsAa' -k "nn_linear"

submit
============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 18 items / 17 deselected                                             

tests/test_nn_and_optim.py 
Submitting nn_linear...
Grader test 1 passed
Grader test 2 passed
Grader test 3 passed
Grader test 4 passed
Grader test 5 passed
Grader test 6 passed
.

=================== 1 passed, 17 deselected in 5.78 seconds ====================


### ReLU
`needle.nn.ReLU()`

Applies the rectified linear unit function element-wise:
$ReLU(x) = max(0, x)$.

If you have previously implemented ReLU's backwards pass in terms of itself, note that this is numerically unstable and will likely cause problems
down the line.
Instead, consider that we could write the derivative of ReLU as $I\{x>0\}$, where we arbitrarily decide that the derivative at $x=0$ is 0.
(This is a _subdifferentiable_ function.)

___

In [ ]:
!python3 -m pytest -v -k "test_nn_relu"

============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 90 items / 88 deselected                                             

tests/test_nn_and_optim.py::test_nn_relu_forward_1 PASSED                [ 50%]
tests/test_nn_and_optim.py::test_nn_relu_backward_1 PASSED               [100%]

=================== 2 passed, 88 deselected in 0.47 seconds ====================


In [ ]:
!python -m mugrade submit '_7GqfAa2TKxH2yZHzgsAa' -k "nn_relu"

submit
============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 18 items / 17 deselected                                             

tests/test_nn_and_optim.py 
Submitting nn_relu...
Grader test 1 passed
PowerScalar gradient
[[1.7  0.15 3.2  4.35]
 [0.85 0.85 0.05 3.95]
 [0.2  4.95 4.1  0.55]]
[[3.4 0.3 6.4 8.7]
 [1.7 1.7 0.1 7.9]
 [0.4 9.9 8.2 1.1]]
end.
Grader test 2 passed
.

=================== 1 passed, 17 deselected in 1.91 seconds ====================


### Sequential
`needle.nn.Sequential(*modules)`

Applies a sequence of modules to the input (in the order that they were passed to the constructor) and returns the output of the last module.
These should be kept in a `.module` property: you should _not_ redefine any magic methods like `__getitem__`, as this may not be compatible with our tests.

##### Parameters
- `*modules` - any number of modules of type `needle.nn.Module`

___

In [ ]:
!python3 -m pytest -v -k "test_nn_sequential"

============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 90 items / 88 deselected                                             

tests/test_nn_and_optim.py::test_nn_sequential_forward_1 PASSED          [ 50%]
tests/test_nn_and_optim.py::test_nn_sequential_backward_1 PASSED         [100%]

=================== 2 passed, 88 deselected in 0.46 seconds ====================


In [ ]:
!python -m mugrade submit '_7GqfAa2TKxH2yZHzgsAa' -k "nn_sequential"

submit
============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 18 items / 17 deselected                                             

tests/test_nn_and_optim.py 
Submitting nn_sequential...
[[4.95 4.5  0.75 4.75 1.4 ]
 [4.5  0.45 1.   3.75 1.1 ]] [[-0.27486882  0.98746556  0.50827324  0.21614991 -0.7536254  -0.75367826
  -0.9681903   0.80225176]
 [ 0.2215319   0.4558642  -1.0503467   1.0295209   0.72834533 -0.6302334
  -0.6970866  -0.693626  ]
 [-0.42888376  0.05423862 -0.14910099 -0.45739403  0.24505742 -0.7898294
  -0.45538825 -0.29278654]
 [-0.09624584  0.62478924 -0.65798175  0.03118609  0.20247018 -0.9936774
   0.23561896 -0.7218455 ]
 [-0.9529242   0.98345894  1.0201486   0.6756647  -0.42806977 -0.88145626
   0.40363434 -0.13111931]]
[[ 0.         11.316259    0.          7.1627684   0.          0.
 

### LogSumExp

`needle.ops.LogSumExp(axes)`

Here you will need to implement one additional operatior in the `python/ops.py` file, as you did in HW1. Applies a numerically stable log-sum-exp function to the input by subtracting off the maximum elements.

\begin{equation}
\text{LogSumExp}(z) = \log (\sum_{i} \exp (z_i - \max{z})) + \max{z}
\end{equation}

#### Parameters
- `axes` - Tuple of axes to sum and take the maximum element over. This uses the same conventions as `needle.ops.Summation()`

___

In [ ]:
!python3 -m pytest -v -k "test_op_logsumexp"

============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 90 items / 80 deselected                                             

tests/test_nn_and_optim.py::test_op_logsumexp_forward_1 PASSED           [ 10%]
tests/test_nn_and_optim.py::test_op_logsumexp_forward_2 PASSED           [ 20%]
tests/test_nn_and_optim.py::test_op_logsumexp_forward_3 PASSED           [ 30%]
tests/test_nn_and_optim.py::test_op_logsumexp_forward_4 PASSED           [ 40%]
tests/test_nn_and_optim.py::test_op_logsumexp_forward_5 PASSED           [ 50%]
tests/test_nn_and_optim.py::test_op_logsumexp_backward_1 PASSED          [ 60%]
tests/test_nn_and_optim.py::test_op_logsumexp_backward_2 PASSED          [ 70%]
tests/test_nn_and_optim.py::test_op_logsumexp_backward_3 PASSED          [ 80%]
tests/

In [ ]:
!python -m mugrade submit '_7GqfAa2TKxH2yZHzgsAa' -k "op_logsumexp"

submit
============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 18 items / 17 deselected                                             

tests/test_nn_and_optim.py 
Submitting op_logsumexp...
Grader test 1 passed
Grader test 2 passed
Grader test 3 passed
Grader test 4 passed
Grader test 5 passed
PowerScalar gradient
5.1138697
10.227739334106445
end.
Grader test 6 passed
PowerScalar gradient
[[2.1  0.95 3.45]
 [3.1  2.45 2.3 ]]
[[4.2 1.9 6.9]
 [6.2 4.9 4.6]]
end.
Grader test 7 passed
PowerScalar gradient
[5.3488064 5.372159 ]
[10.697613 10.744318]
end.
Grader test 8 passed
PowerScalar gradient
[5.958662]
[11.917324]
end.
Grader test 9 passed
PowerScalar gradient
[[4.3532043 4.464995 ]
 [4.842827  4.5603485]]
[[8.7064085 8.92999  ]
 [9.685654  9.120697 ]]
end.
Grader test 10 passed
.

=================== 1 pass

### SoftmaxLoss

`needle.nn.SoftmaxLoss()`

Applies the softmax loss as defined below (and as implemented in Homework 1), taking in as input a Tensor of logits and a Tensor of the true labels (expressed as a list of numbers, *not* one-hot encoded).

Note that you can use the `init.one_hot` function now instead of writing this yourself.  Note: You will need to use the numerically stable logsumexp operated you just implemented for this purpose.

\begin{equation}
\ell_\text{softmax}(z,y) = \log \sum_{i=1}^k \exp z_i - z_y
\end{equation}

___

In [110]:
!python3 -m pytest -v -k "test_nn_softmax_loss"

============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 90 items / 86 deselected                                             

tests/test_nn_and_optim.py::test_nn_softmax_loss_forward_1 FAILED        [ 25%]
tests/test_nn_and_optim.py::test_nn_softmax_loss_forward_2 FAILED        [ 50%]
tests/test_nn_and_optim.py::test_nn_softmax_loss_backward_1 PASSED       [ 75%]
tests/test_nn_and_optim.py::test_nn_softmax_loss_backward_2 PASSED       [100%]

=================================== FAILURES ===================================
________________________ test_nn_softmax_loss_forward_1 ________________________

    def test_nn_softmax_loss_forward_1():
>       np.testing.assert_allclose(softmax_loss_forward(5, 10),
            np.array(4.041218, dtype=np.float32), rtol=1

In [ ]:
!python -m mugrade submit '_7GqfAa2TKxH2yZHzgsAa' -k "nn_softmax_loss"

submit
============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 18 items / 17 deselected                                             

tests/test_nn_and_optim.py 
Submitting nn_softmax_loss...
[[4.4  0.95 2.3  3.7  4.7  3.45 3.95 1.3  0.35]
 [1.45 1.05 2.25 0.6  4.   3.6  1.4  2.65 3.25]
 [1.3  3.2  3.55 4.8  1.7  3.05 2.6  1.55 0.1 ]
 [3.35 0.75 4.85 4.75 2.7  0.85 4.7  3.6  2.2 ]]
[7 5 1 8]
Grader test 1 passed
[[0.05 0.25 1.1  1.6  0.15 4.35 0.6 ]
 [3.2  2.55 1.15 0.6  3.45 0.4  1.2 ]]
[0 5]
Grader test 2 passed
[[4.4  0.95 2.3  3.7  4.7  3.45 3.95 1.3  0.35]
 [1.45 1.05 2.25 0.6  4.   3.6  1.4  2.65 3.25]
 [1.3  3.2  3.55 4.8  1.7  3.05 2.6  1.55 0.1 ]
 [3.35 0.75 4.85 4.75 2.7  0.85 4.7  3.6  2.2 ]]
[7 5 1 8]
Grader test 3 passed
[[0.05 0.25 1.1  1.6  0.15 4.35 0.6 ]
 [3.2  2.55 1.15 0.6  3.45 0.4  1.2

### LayerNorm1d
`needle.nn.LayerNorm1d(dim, eps=1e-5, device=None, dtype="float32")`

Applies layer normalization over a mini-batch of inputs as described in the paper [Layer Normalization](https://arxiv.org/abs/1607.06450).

\begin{equation}
y = w \circ \frac{x_i - \textbf{E}[x]}{((\textbf{Var}[x]+\epsilon)^{1/2})} + b
\end{equation}

where $\textbf{E}[x]$ denotes the empirical mean of the inputs, $\textbf{Var}[x]$ denotes their empirical variance (not that here we are using the "unbiased" estimate of the variance, i.e., dividing by $N$ rather than by $N-1$), and $w$ and $b$ denote learnable scalar weights and biases respectively.  Note you can assume the input to this layer by be a 2D tensor, with batches in the first dimension and features on the second.

##### Parameters
- `dim` - number of channels
- `eps` - a value added to the denominator for numerical stability.

##### Variables
- `weight` - the learnable weights of size `dim`, elements initialized to 1.
- `bias` - the learnable bias of shape `dim`, elements initialized to 0 **(changed from 1)**.
___

In [ ]:
!python3 -m pytest -v -k "test_nn_layernorm"

============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 90 items / 83 deselected                                             

tests/test_nn_and_optim.py::test_nn_layernorm_forward_1 PASSED           [ 14%]
tests/test_nn_and_optim.py::test_nn_layernorm_forward_2 PASSED           [ 28%]
tests/test_nn_and_optim.py::test_nn_layernorm_forward_3 PASSED           [ 42%]
tests/test_nn_and_optim.py::test_nn_layernorm_backward_1 PASSED          [ 57%]
tests/test_nn_and_optim.py::test_nn_layernorm_backward_2 PASSED          [ 71%]
tests/test_nn_and_optim.py::test_nn_layernorm_backward_3 PASSED          [ 85%]
tests/test_nn_and_optim.py::test_nn_layernorm_backward_4 PASSED          [100%]

=================== 7 passed, 83 deselected in 0.54 seconds ====================


In [ ]:
!python -m mugrade submit '_7GqfAa2TKxH2yZHzgsAa' -k "nn_layernorm"

submit
============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 18 items / 17 deselected                                             

tests/test_nn_and_optim.py 
Submitting nn_layernorm...
Grader test 1 passed
Grader test 2 passed
Grader test 3 passed
Grader test 4 passed
Grader test 5 passed
Grader test 6 passed
Grader test 7 passed
Grader test 8 passed
.

=================== 1 passed, 17 deselected in 7.77 seconds ====================



### Flatten
`needle.nn.Flatten()`

Takes in a tensor of shape `(B,X_0,X_1,...)`, and flattens all non-batch dimensions so that the output is of shape `(B, X_0 * X_1 * ...)`

In [ ]:
!python3 -m pytest -v -k "test_nn_flatten"

============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 90 items / 81 deselected                                             

tests/test_nn_and_optim.py::test_nn_flatten_forward_1 PASSED             [ 11%]
tests/test_nn_and_optim.py::test_nn_flatten_forward_2 PASSED             [ 22%]
tests/test_nn_and_optim.py::test_nn_flatten_forward_3 PASSED             [ 33%]
tests/test_nn_and_optim.py::test_nn_flatten_forward_4 PASSED             [ 44%]
tests/test_nn_and_optim.py::test_nn_flatten_backward_1 PASSED            [ 55%]
tests/test_nn_and_optim.py::test_nn_flatten_backward_2 PASSED            [ 66%]
tests/test_nn_and_optim.py::test_nn_flatten_backward_3 PASSED            [ 77%]
tests/test_nn_and_optim.py::test_nn_flatten_backward_4 PASSED            [ 88%]
tests/

In [ ]:
!python -m mugrade submit '_7GqfAa2TKxH2yZHzgsAa' -k "nn_flatten"

submit
============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 18 items / 17 deselected                                             

tests/test_nn_and_optim.py 
Submitting nn_flatten...
Grader test 1 passed
Grader test 2 passed
Grader test 3 passed
Grader test 4 passed
Grader test 5 passed
Grader test 6 passed
Grader test 7 passed
Grader test 8 passed
.

=================== 1 passed, 17 deselected in 7.68 seconds ====================


### BatchNorm1d
`needle.nn.BatchNorm1d(dim, eps=1e-5, momentum=0.1, device=None, dtype="float32")`

Applies batch normalization over a mini-batch of inputs as described in the paper [Batch Normalization: Accelerating Deep Network Training by Reducing Internal Covariate Shift](https://arxiv.org/abs/1502.03167).

\begin{equation}
y = w \circ \frac{z_i - \textbf{E}[x]}{((\textbf{Var}[x]+\epsilon)^{1/2})} + b
\end{equation}

but where here the mean and variance refer to to the mean and variance over the _batch_dimensions.  The function also computes a running average of mean/variance for all features at each layer $\hat{\mu}, \hat{\sigma}^2$, and at test time normalizes by these quantities:

\begin{equation}
y = \frac{(x - \hat{mu})}{((\hat{\sigma}^2_{i+1})_j+\epsilon)^{1/2}}
\end{equation}


BatchNorm uses the running estimates of mean and variance instead of batch statistics at test time, i.e.,
after `model.eval()` has been called on the BatchNorm layer's `training` flag is false.

To compute the running estimates, you can use the equation $$\hat{x_{new}} = (1 - m) \hat{x_{old}} + mx_{observed},$$
where $m$ is momentum.

##### Parameters
- `dim` - input dimension
- `eps` - a value added to the denominator for numerical stability.
- `momentum` - the value used for the running mean and running variance computation.

##### Variables
- `weight` - the learnable weights of size `dim`, elements initialized to 1.
- `bias` - the learnable bias of size `dim`, elements initialized to 0.
- `running_mean` - the running mean used at evaluation time, elements initialized to 0.
- `running_var` - the running (unbiased) variance used at evaluation time, elements initialized to 1. 

___

In [ ]:
!python3 -m pytest -v -k "test_nn_batchnorm"

============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 90 items / 82 deselected                                             

tests/test_nn_and_optim.py::test_nn_batchnorm_check_model_eval_switches_training_flag_1 PASSED [ 12%]
tests/test_nn_and_optim.py::test_nn_batchnorm_forward_1 PASSED           [ 25%]
tests/test_nn_and_optim.py::test_nn_batchnorm_forward_affine_1 PASSED    [ 37%]
tests/test_nn_and_optim.py::test_nn_batchnorm_backward_1 PASSED          [ 50%]
tests/test_nn_and_optim.py::test_nn_batchnorm_backward_affine_1 PASSED   [ 62%]
tests/test_nn_and_optim.py::test_nn_batchnorm_running_mean_1 PASSED      [ 75%]
tests/test_nn_and_optim.py::test_nn_batchnorm_running_var_1 PASSED       [ 87%]
tests/test_nn_and_optim.py::test_nn_batchnorm_running_grad_1 PAS

In [ ]:
!python -m mugrade submit '_7GqfAa2TKxH2yZHzgsAa' -k "nn_batchnorm"

submit
============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 18 items / 17 deselected                                             

tests/test_nn_and_optim.py 
Submitting nn_batchnorm...
Grader test 1 passed
Grader test 2 passed
Grader test 3 passed
Grader test 4 passed
Grader test 5 passed
Grader test 6 passed
Grader test 7 passed
Grader test 8 passed
Grader test 9 passed
.

=================== 1 passed, 17 deselected in 10.54 seconds ===================


### Dropout
`needle.nn.Dropout(p = 0.5)`

During training, randomly zeroes some of the elements of the input tensor with probability `p` using samples from a Bernoulli distribution. This has proven to be an effective technique for regularization and preventing the co-adaptation of neurons as described in the paper [Improving neural networks by preventing co-adaption of feature detectors](https://arxiv.org/abs/1207.0580). During evaluation the module simply computes an identity function. 

\begin{equation}
\hat{z}_{i+1} = \sigma_i (W_i^T z_i + b_i) \\
(z_{i+1})_j = 
    \begin{cases}
    (\hat{z}_{i+1})_j /(1-p) & \text{with probability } 1-p \\
    0 & \text{with probability } p \\
    \end{cases}
\end{equation}

**Important**: If the Dropout module the flag `training=False`, you shouldn't "dropout" any weights. That is, dropout applies during training only, not during evaluation. Note that `training` is a flag in `nn.Module`.

##### Parameters
- `p` - the probability of an element to be zeroed.

___

In [ ]:
!python3 -m pytest -v -k "test_nn_dropout"

============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 90 items / 88 deselected                                             

tests/test_nn_and_optim.py::test_nn_dropout_forward_1 PASSED             [ 50%]
tests/test_nn_and_optim.py::test_nn_dropout_backward_1 PASSED            [100%]

=================== 2 passed, 88 deselected in 0.69 seconds ====================


In [ ]:
!python -m mugrade submit '_7GqfAa2TKxH2yZHzgsAa' -k "nn_dropout"

submit
============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 18 items / 17 deselected                                             

tests/test_nn_and_optim.py 
Submitting nn_dropout...
[ True  True  True False False  True  True  True  True]
<Reshape compute>: (9,) (3, 3)
Grader test 1 passed
[ True  True  True  True False  True  True  True  True]
<Reshape compute>: (9,) (3, 3)
summation gradient calling reshape  1.0 (1, 1)
1.0
<Reshape compute>: () (1, 1)
<BroadcastTo compute>: (1, 1) (3, 3)
Grader test 2 passed
.

=================== 1 passed, 17 deselected in 3.61 seconds ====================


### Residual
`needle.nn.Residual(fn: Module)`

Applies a residual or skip connection given module $\mathcal{F}$ and input Tensor $x$, returning $\mathcal{F}(x) + x$.
##### Parameters
- `fn` - module of type `needle.nn.Module`

In [ ]:
!python3 -m pytest -v -k "test_nn_residual"

============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 90 items / 88 deselected                                             

tests/test_nn_and_optim.py::test_nn_residual_forward_1 PASSED            [ 50%]
tests/test_nn_and_optim.py::test_nn_residual_backward_1 PASSED           [100%]

=================== 2 passed, 88 deselected in 0.48 seconds ====================


In [ ]:
!python -m mugrade submit '_7GqfAa2TKxH2yZHzgsAa' -k "nn_residual"

submit
============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 18 items / 17 deselected                                             

tests/test_nn_and_optim.py 
Submitting nn_residual...
Grader test 1 passed
Grader test 2 passed
.

=================== 1 passed, 17 deselected in 2.55 seconds ====================


## Question 3

Implement the `step` function of the following optimizers.
Make sure that your optimizers _don't_ modify the gradients of tensors in-place.

We have included some tests to ensure that you are not consuming excessive memory, which can happen if you are
not using `.data` or `.detach()` in the right places, thus building an increasingly large computational graph
(not just in the optimizers, but in the previous modules as well).
You can ignore these tests, which include the string `memory_check` at your own discretion.

___

### SGD
`needle.optim.SGD(params, lr=0.01, momentum=0.0, weight_decay=0.0)`

Implements stochastic gradient descent (optionally with momentum, shown as $\beta$ below). 

\begin{equation}
\begin{split}
    u_{t+1} &= \beta u_t + (1-\beta) \nabla_\theta f(\theta_t) \\
    \theta_{t+1} &= \theta_t - \alpha u_{t+1}
\end{split}
\end{equation}

##### Parameters
- `params` - iterable of parameters of type `needle.nn.Parameter` to optimize
- `lr` (*float*) - learning rate
- `momentum` (*float*) - momentum factor
- `weight_decay` (*float*) - weight decay (L2 penalty)
___

In [ ]:
!python3 -m pytest -v -k "test_optim_sgd"

============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 90 items / 84 deselected                                             

tests/test_nn_and_optim.py::test_optim_sgd_vanilla_1 PASSED              [ 16%]
tests/test_nn_and_optim.py::test_optim_sgd_momentum_1 PASSED             [ 33%]
tests/test_nn_and_optim.py::test_optim_sgd_weight_decay_1 PASSED         [ 50%]
tests/test_nn_and_optim.py::test_optim_sgd_momentum_weight_decay_1 PASSED [ 66%]
tests/test_nn_and_optim.py::test_optim_sgd_layernorm_residual_1 PASSED   [ 83%]
tests/test_nn_and_optim.py::test_optim_sgd_z_memory_check_1 PASSED       [100%]

=================== 6 passed, 84 deselected in 1.16 seconds ====================


In [3]:
!python -m mugrade submit '_7GqfAa2TKxH2yZHzgsAa' -k "optim_sgd"

流式输出内容被截断，只能显示最后 5000 行内容。
 [-4.440351   -3.9248362   0.34126937  0.10754013 -1.80201    -5.697944
  -6.7916927  -4.544771  ]
 [ 1.8152629  -4.9209504  -3.9084034  -3.4515214  -4.4769626  -1.4818953
  -1.6701151   0.5833568 ]]
[[ -3.2459364   -3.4022934   -4.7065525   -6.3610253   -2.7815642
   -2.4477115   -3.8571506   -4.846932  ]
 [ -2.0713115   -4.833464    -3.6269493   -3.9233456    0.24695103
   -2.9922154   -5.425137    -0.9998182 ]
 [ -2.5505557   -4.8626847   -1.1410489   -0.7041566   -4.0521903
   -3.319003    -5.2229915   -1.61843   ]
 [ -2.497212    -4.2748704   -3.285407    -0.50666237  -2.130628
   -2.4136248   -3.8688588   -0.5411247 ]
 [ -2.4340887   -5.8839135  -10.238892    -3.0962315   -4.7697997
   -4.811373    -5.2992907   -5.6484714 ]
 [ -4.8319497   -1.8441627   -1.3101513   -3.7393637   -2.941449
   -3.71844     -0.60886675  -2.0801718 ]
 [ -1.138298    -3.0652766   -1.2091656   -1.901634    -1.3384415
   -0.19211316  -4.537503    -1.6634995 ]
 [ -2.9371257   -5

### Adam
`needle.optim.Adam(params, lr=0.01, beta1=0.9, beta2=0.999, eps=1e-8, weight_decay=0.0)`

Implements Adam algorithm, proposed in [Adam: A Method for Stochastic Optimization](https://arxiv.org/abs/1412.6980). 

\begin{equation}
\begin{split}
u_{t+1} &= \beta_1 u_t + (1-\beta_1) \nabla_\theta f(\theta_t) \\
v_{t+1} &= \beta_2 v_t + (1-\beta_2) (\nabla_\theta f(\theta_t))^2 \\
\hat{u}_{t+1} &= u_{t+1} / (1 - \beta_1^t) \quad \text{(bias correction)} \\
\hat{v}_{t+1} &= v_{t+1} / (1 - \beta_2^t) \quad \text{(bias correction)}\\
\theta_{t+1} &= \theta_t - \alpha \hat{u_{t+1}}/(\hat{v}_{t+1}^{1/2}+\epsilon)
\end{split}
    \end{equation}

**Important:** Pay attention to whether or not you are applying bias correction.

##### Parameters
- `params` - iterable of parameters of type `needle.nn.Parameter` to optimize
- `lr` (*float*) - learning rate
- `beta1` (*float*) - coefficient used for computing running average of gradient
- `beta2` (*float*) - coefficient used for computing running average of square of gradient
- `eps` (*float*) - term added to the denominator to improve numerical stability
- `bias_correction` - whether to use bias correction for $u, v$
- `weight_decay` (*float*) - weight decay (L2 penalty)

In [7]:
!python3 -m pytest -v -k "test_optim_adam"

============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 90 items / 83 deselected                                             

tests/test_nn_and_optim.py::test_optim_adam_1 PASSED                     [ 14%]
tests/test_nn_and_optim.py::test_optim_adam_weight_decay_1 PASSED        [ 28%]
tests/test_nn_and_optim.py::test_optim_adam_batchnorm_1 PASSED           [ 42%]
tests/test_nn_and_optim.py::test_optim_adam_batchnorm_eval_mode_1 PASSED [ 57%]
tests/test_nn_and_optim.py::test_optim_adam_layernorm_1 PASSED           [ 71%]
tests/test_nn_and_optim.py::test_optim_adam_weight_decay_bias_correction_1 PASSED [ 85%]
tests/test_nn_and_optim.py::test_optim_adam_z_memory_check_1 PASSED      [100%]

=================== 7 passed, 83 deselected in 1.02 seconds ================

In [9]:
!python -m mugrade submit '_7GqfAa2TKxH2yZHzgsAa' -k "optim_adam"

submit
============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 18 items / 17 deselected                                             

tests/test_nn_and_optim.py 
Submitting optim_adam...
Grader test 1 passed
Grader test 2 passed
Grader test 3 passed
Grader test 4 passed
Grader test 5 passed
Grader test 6 passed
.

=================== 1 passed, 17 deselected in 6.22 seconds ====================


## Question 4

In this question, you will implement two data primitives: `needle.data.DataLoader` and `needle.data.Dataset`. `Dataset` stores the samples and their corresponding labels, and `DataLoader` wraps an iterable around the `Dataset` to enable easy access to the samples. 

For this question, you will be working in `python/needle/data.py`. First, copy your solution to `parse_mnist` from the previous homework into the `parse_mnist` function. 

### Transformations

First we will implement a few transformations that are helpful when working with images. We will stick with a horizontal flip and a random crop for now. Fill out the following functions in `data.py`.
___ 

#### RandomFlipHorizontal
`needle.data.RandomFlipHorizontal(p = 0.5)`

Flips the image horizontally, with probability `p`.

##### Parameters
- `p` (*float*) - The probability of flipping the input image.
___

#### RandomCrop
`needle.data.RandomCrop(padding=3)`

Padding is added to all side of the image, and then the image is cropped back to it's original size at a random location. Returns an image the same size as the original image.

##### Parameters
- `padding` (*int*) - The padding on each border of the image.

In [21]:
!python3 -m pytest -v -k "flip_horizontal"
!python3 -m pytest -v -k "random_crop"

============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 90 items / 89 deselected                                             

tests/test_data.py::test_flip_horizontal PASSED                          [100%]

=================== 1 passed, 89 deselected in 0.59 seconds ====================
============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 90 items / 89 deselected                                             

tests/test_data.py::test_random_crop PASSED                              [100%]

=================== 1 passed, 89 deselected in 0.

In [22]:
!python -m mugrade submit '_7GqfAa2TKxH2yZHzgsAa' -k "flip_horizontal"
!python -m mugrade submit '_7GqfAa2TKxH2yZHzgsAa' -k "random_crop"

submit
============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 18 items / 17 deselected                                             

tests/test_data.py 
Submitting flip_horizontal...
Grader test 1 passed
Grader test 2 passed
Grader test 3 passed
Grader test 4 passed
Grader test 5 passed
Grader test 6 passed
.

=================== 1 passed, 17 deselected in 4.93 seconds ====================
submit
============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 18 items / 17 deselected                                             

tests/test_data.py 
Submitting random_crop...
Grader test 1 passed
Grader test 2 passed
Grader test 3 pass

### Dataset

Each `Dataset` subclass must implement three functions: `__init__`, `__len__`, and `__getitem__`. The `__init__` function initializes the images, labels, and transforms. The `__len__` function returns the number of samples in the dataset. The `__getitem__` function retrieves a sample from the dataset at a given index `idx`, calls the transform functions on the image (if applicable), converts the image and label to a numpy array (the data will be converted to Tensors elsewhere). Fill out these functions in the `MNISTDataset` class: 
___ 

### MNISTDataset
`needle.data.MNISTDataset(image_filesname, label_filesname, transforms)`

##### Parameters
- `image_filesname` - path of file containing images
- `label_filesname` - path of file containing labels
- `transforms` - an optional list of transforms to apply to data


In [64]:
!python3 -m pytest -v -k "test_mnist_dataset"

============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 90 items / 89 deselected                                             

tests/test_data.py::test_mnist_dataset PASSED                            [100%]

=================== 1 passed, 89 deselected in 82.81 seconds ===================


In [65]:
!python -m mugrade submit '_7GqfAa2TKxH2yZHzgsAa' -k "mnist_dataset"

submit
============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 18 items / 17 deselected                                             

tests/test_data.py 
Submitting mnist_dataset...
Grader test 1 failed: Failed: incorrect output
Grader test 2 passed
Grader test 3 passed
Grader test 4 passed
Grader test 5 passed
Grader test 6 passed
Grader test 7 passed
Grader test 8 passed
Grader test 9 passed
Grader test 10 passed
F

=================================== FAILURES ===================================
_____________________________ submit_mnist_dataset _____________________________
<Failed instance>
=================== 1 failed, 17 deselected in 92.96 seconds ===================


### Dataloader

The Dataloader class provides an interface for assembling mini-batches of examples suitable for training using SGD-based approaches, backed by a Dataset object.  In order to build the typical Dataloader interface (allowing users to iterate over all the mini-batches in the dataset), you will need the implement the `__iter__()` and `__next__()` calls in the class: `__iter__()` is called at the start of iteration, while `__next__()` is called to grab the next mini-batch. Please note that subsequent calls to next will require you to return the following batches, so next is not a pure function.
___

### Dataloader
`needle.data.Dataloader(dataset: Dataset, batch_size: Optional[int] = 1, shuffle: bool = False)`

Combines a dataset and a sampler, and provides an iterable over the given dataset. 

##### Parameters
- `dataset` - `needle.data.Dataset` - a dataset 
- `batch_size` - `int` - what batch size to serve the data in 
- `shuffle` - `bool` - set to ``True`` to have the data reshuffle at every epoch, default ``False``.
___ 





In [111]:
!python3 -m pytest -v -k "test_dataloader"

============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 90 items / 88 deselected                                             

tests/test_data.py::test_dataloader_mnist PASSED                         [ 50%]
tests/test_data.py::test_dataloader_ndarray PASSED                       [100%]

=================== 2 passed, 88 deselected in 45.77 seconds ===================


In [98]:
!python -m mugrade submit '_7GqfAa2TKxH2yZHzgsAa' -k "dataloader"

submit
============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 18 items / 17 deselected                                             

tests/test_data.py 
Submitting dataloader...
[    0     1     2 ... 59997 59998 59999]
Grader test 1 passed
[   0    1    2 ... 9997 9998 9999]
Grader test 2 passed
Grader test 3 passed
[   0    1    2 ... 9997 9998 9999]
Grader test 4 passed
Grader test 5 passed
.

=================== 1 passed, 17 deselected in 36.35 seconds ===================


## Question 5

Given you have now implemented all the necessary components for our neural network library, let's build and train an MLP ResNet. For this question, you will be working in `apps/mlp_resnet.py`. First, fill out the functions `ResidualBlock` and `MLPResNet` as described below:

### ResidualBlock
`ResidualBlock(dim, hidden_dim, norm=nn.BatchNorm1d, drop_prob=0.1)`

Implements a residual block as follows:

![](https://github.com/dlsyscourse/hw2/blob/master/figures/residualblock.png?raw=1)

where the first linear layer has `in_features=dim` and `out_features=hidden_dim`, and the last linear layer has `out_features=dim`. Returns the block as type `nn.Module`. 

##### Parameters
- `dim` (*int*) - input dim
- `hidden_dim` (*int*) - hidden dim
- `norm` (*nn.Module*) - normalization method
- `drop_prob` (*float*) - dropout probability

___

### MLPResNet
`MLPResNet(dim, hidden_dim=100, num_blocks=3, num_classes=10, norm=nn.BatchNorm1d, drop_prob=0.1)`

Implements an MLP ResNet as follows:

![](https://github.com/dlsyscourse/hw2/blob/master/figures/mlp_resnet.png?raw=1)

where the first linear layer has `in_features=dim` and `out_features=hidden_dim`, and each ResidualBlock has `dim=hidden_dim` and `hidden_dim=hidden_dim//2`. Returns a network of type `nn.Module`.

##### Parameters
- `dim` (*int*) - input dim
- `hidden_dim` (*int*) - hidden dim
- `num_blocks` (*int*) - number of ResidualBlocks
- `num_classes` (*int*) - number of classes
- `norm` (*nn.Module*) - normalization method
- `drop_prob` (*float*) - dropout probability (0.1)
___ 

Once you have the deep learning model architecture correct, let's train the network using our new neural network library components. Specifically, implement the functions `epoch` and `train_mnist`.

### Epoch

`epoch(dataloader, model, opt=None)`

Executes one epoch of training or evaluation, iterating over the entire training dataset once (just like `nn_epoch` from previous homeworks). Returns the average error rate **(changed from accuracy)** (as a *float*) and the average loss over all samples (as a *float*). Set the model to `training` mode at the beginning of the function if `opt` is given; set the model to `eval` if `opt` is not given (i.e. `None`).

##### Parameters
- `dataloader` (*`needle.data.DataLoader`*) - dataloader returning samples from the training dataset
- `model` (*`needle.nn.Module`*) - neural network
- `opt` (*`needle.optim.Optimizer`*) - optimizer instance, or `None`

___

### Train Mnist

`train_mnist(batch_size=100, epochs=10, optimizer=ndl.optim.Adam, lr=0.001, weight_decay=0.001, hidden_dim=100, data_dir="data")`
                
Initializes a training dataloader (with `shuffle` set to `True`) and a test dataloader for MNIST data, and trains an `MLPResNet` using the given optimizer (if `opt` is not None) and the softmax loss for a given number of epochs. Returns a tuple of the training accuracy, training loss, test accuracy, test loss computed in the last epoch of training. If any parameters are not specified, use the default parameters.

##### Parameters
- `batch_size` (*int*) - batch size to use for train and test dataloader
- `epochs` (*int*) - number of epochs to train for
- `optimizer` (*`needle.optim.Optimizer` type*) - optimizer type to use
- `lr` (*float*) - learning rate 
- `weight_decay` (*float*) - weight decay
- `hidden_dim` (*int*) - hidden dim for `MLPResNet`
- `data_dir` (*int*) - directory containing MNIST image/label files


In [24]:
!python3 -m pytest -v -k "test_mlp"

============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 90 items / 80 deselected                                             

tests/test_nn_and_optim.py::test_mlp_residual_block_num_params_1 PASSED  [ 10%]
tests/test_nn_and_optim.py::test_mlp_residual_block_num_params_2 PASSED  [ 20%]
tests/test_nn_and_optim.py::test_mlp_residual_block_forward_1 PASSED     [ 30%]
tests/test_nn_and_optim.py::test_mlp_resnet_num_params_1 PASSED          [ 40%]
tests/test_nn_and_optim.py::test_mlp_resnet_num_params_2 PASSED          [ 50%]
tests/test_nn_and_optim.py::test_mlp_resnet_forward_1 PASSED             [ 60%]
tests/test_nn_and_optim.py::test_mlp_resnet_forward_2 PASSED             [ 70%]
tests/test_nn_and_optim.py::test_mlp_train_epoch_1 PASSED                [ 80%]
tests/

In [23]:
!python -m mugrade submit '_7GqfAa2TKxH2yZHzgsAa' -k "mlp_resnet"

submit
============================= test session starts ==============================
platform linux -- Python 3.7.15, pytest-3.6.4, py-1.11.0, pluggy-0.7.1
rootdir: /content/drive/MyDrive/10714/hw2, inifile:
plugins: typeguard-2.7.1
collected 18 items / 17 deselected                                             

tests/test_nn_and_optim.py 
Submitting mlp_resnet...
Grader test 1 passed
Grader test 2 passed
Grader test 3 passed
Grader test 4 passed
Grader test 5 passed
Grader test 6 passed
Grader test 7 passed
Grader test 8 passed
Grader test 9 passed
TrainingErr:  0.7949124270225187  TrainingLoss:  2.3004774281738003
0.7949124270225187 2.3004774281738003 0.7308080808080808 1.9530581765704684
Grader test 10 failed: Failed: incorrect output
F

=================================== FAILURES ===================================
______________________________ submit_mlp_resnet _______________________________
<Failed instance>
=================== 1 failed, 17 deselected in 81.13 seconds =====

We encourage to experiment with the `mlp_resnet.py` training script.
You can investigate the effect of using different initializers on the Linear layers,
increasing the dropout probability,
or adding transforms (via a list to the `transforms=` keyword argument of Dataset)
such as random cropping.